name: deployment2
on: [push, workflow_dispatch]
jobs:
  deps-install:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
  run-code:
    runs-on: ubuntu-latest
    needs: deps-install
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: lint project
        run: npm run lint
      - name: test
        run: npm run test
  deploy-code:
    runs-on: ubuntu-latest
    needs: deps-install
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Build Project
        run: npm run build
