name: deployment2
on: [push, workflow_dispatch]

jobs:
  deps-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Save node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

  run-code:
    runs-on: ubuntu-latest
    needs: deps-install
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Lint Project
        run: npm run lint
      - name: Run Tests
        run: npm run test

  deploy-code:
    runs-on: ubuntu-latest
    needs: run-code
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies (build needs them)
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploying the Project
        run: echo "deploying to aws ....."
